### PR TITLE
Add video downloading

### PR DESCRIPTION
**Pull request by error454**
I've added video downloading. I had to move the selenium driver close command over to the class destructor to facilitate this as video downloading requires making new requests.

I wasn't sure how to manage the count parameter, as-is downloaded photos don't count towards the total for video downloading. Let me know if I can refactor this to fit more with the project.

### CODE REVIEW

**Comment by akurtovic** [comment]
Great. I'll look it over as soon as I get a chance and merge it in if there are no big changes required.

**Comment by error454** [comment]
Looks like instagram went and changed all their classnames last night. So everything is not working now, I'll have to redo this.

**Comment by error454** [comment]
Updated video classes, also fixed the "Load More" class

**Comment by akurtovic** [comment]
Thanks for making the fix and being on top of it. I'm going to merge this in but I'm afraid given the class name there that they've added a step in the minification process to randomly rename the classes with short names. If I'm right, the selectors will keep breaking every time they minify and deploy. :-(

**Comment by error454** [comment]
I'm afraid you are correct. We might be able to find some elements in a way that would let us infer the classnames. This would only move the breakpoint to the nested structure, so changes that are significant could still cause breakage, but that's the nature of these types of projects :)

**Comment by akurtovic** [comment]
Yes, I agree. I've played with the idea of using XPath selectors in the past, but if the structure changes and the class names don't you're in the same boat.

**Pull request merged**
